name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.x'
          cache: 'npm'

      - name: Install dependencies
        run: pnpm setup
      
      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release